name: Metrics Automation Script

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }} 

      - name: Pick 3-4 random days for this week
        id: randomdays
        run: |
          NUM_COMMITS=$((3 + RANDOM % 2))
          DAYS=($(shuf -i 1-7 -n $NUM_COMMITS))
          echo "RANDOM_DAYS=${DAYS[*]}" >> $GITHUB_ENV
          echo "Picked days: ${DAYS[*]}"

      - name: Check if today is a commit day
        id: checkday
        run: |
          TODAY=$(date +'%u')
          if [[ " $RANDOM_DAYS " =~ " $TODAY " ]]; then
            echo "RUN_JOB=true" >> $GITHUB_ENV
          else
            echo "RUN_JOB=false" >> $GITHUB_ENV
          fi

      - name: Update WakaTime README
        # if: env.RUN_JOB == 'true' && github.event_name == 'schedule'
        if: always()
        uses: sumitverma77/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: false 
          SHOW_PROFILE_VIEWS: false
          SHOW_PROJECTS: false
          SHOW_OS: false
          SHOW_SHORT_INFO: false
          COMMIT_BY_ME: true
          COMMIT_USERNAME: "sumitverma77"
          COMMIT_EMAIL: "987sumitverma@gmail.com"
      # - name: Commit & push with randomized time
      #   if: env.RUN_JOB == 'true'
      #   run: |
      #     HOUR=$((RANDOM % 24))
      #     MINUTE=$((RANDOM % 60))
      #     DATE=$(date -u +"%Y-%m-%dT$HOUR:$MINUTE:00Z")
      #     git config user.name "Sumit Verma"
      #     git config user.email "987sumitverma@gmail.com"
      #     git fetch origin main
      #     git reset --hard origin/main
      #     git add README.md
      #     git commit -m "Random WakaTime update" --date="$DATE" || echo "No changes to commit"
      #     git push origin main
      
      
      #
